import {EVENT_PLAYER_SLOTS} from './constants';
import {resolveEventCoverUrl} from './eventCovers';
import type {AppUser, ForzaEvent} from './types';

export const MOCK_USER: AppUser = {
  discordId: '100000000000000001',
  username: 'KVFIR',
  xboxGamertag: 'KVFIR',
  eventsJoined: 63,
  eventsHosted: 14,
  attendanceRate: 92,
  noShows: 2,
  hostRatingAvg: 4.7,
};

const day = 24 * 60 * 60 * 1000;

const MOCK_EVENTS_RAW: ForzaEvent[] = [
  {
    id: 'evt-1',
    slug: 'street-cup-20260510',
    title: 'A-Class Street Racing Cup',
    type: 'road',
    status: 'open',
    lifecycle: 'open',
    createdAt: new Date(Date.now() - 2 * day).toISOString(),
    startsAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    maxPlayers: EVENT_PLAYER_SLOTS,
    currentPlayers: 8,
    carRuleMode: 'restricted_list',
    maxPi: 800,
    allowedCars: [
      {
        carId: 'c1',
        make: 'BMW',
        model: 'M3',
        year: 1997,
        pi: 549,
        maxPi: 800,
        restrictions: ['No Forza aero'],
      },
      {
        carId: 'c1b',
        make: 'Porsche',
        model: '911 GT3',
        year: 2022,
        pi: 780,
        maxPi: 800,
        tuneShareCode: '111 222 333',
        restrictions: [],
      },
      {
        carId: 'c1c',
        make: 'Mercedes-Benz',
        model: '190E',
        year: 1990,
        pi: 512,
        maxPi: 650,
        restrictions: ['No engine swap'],
      },
      {
        carId: 'c1d',
        make: 'Honda',
        model: 'Civic Type R',
        year: 2023,
        pi: 598,
        maxPi: 700,
        restrictions: [],
      },
      {
        carId: 'c1e',
        make: 'Mazda',
        model: 'RX-7',
        year: 1997,
        pi: 641,
        maxPi: 750,
        tuneShareCode: '444 555 666',
        restrictions: ['No Forza aero'],
      },
    ],
    voicePolicy: 'required',
    hostDiscordId: '200000000000000002',
    hostUsername: 'Horizon Latvia Club',
    rules: 'Clean racing only.',
    description: 'Night street cup for A-class builds.',
    trackCodes: ['123 456 789', '234 567 890'],
    lobbyLeaderGamertag: 'HostGT',
    participants: [{discordId: MOCK_USER.discordId, username: MOCK_USER.username}],
  },
  {
    id: 'evt-2',
    slug: 'rally-sprint-20260511',
    title: 'Rally Sprint',
    type: 'dirt',
    status: 'ended',
    lifecycle: 'completed',
    createdAt: new Date(Date.now() - 5 * day).toISOString(),
    startsAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    maxPlayers: EVENT_PLAYER_SLOTS,
    currentPlayers: 5,
    carRuleMode: 'restricted_list',
    maxPi: 650,
    allowedCars: [
      {
        carId: 'c2',
        make: 'Subaru',
        model: 'WRX STI',
        year: 2015,
        pi: 550,
        maxPi: 650,
        tuneShareCode: '987 654 321',
        restrictions: [],
      },
    ],
    voicePolicy: 'optional',
    hostDiscordId: MOCK_USER.discordId,
    hostUsername: MOCK_USER.username,
    rules: 'Prescribed tune per car.',
    trackCodes: ['111 222 333'],
    participants: [
      {discordId: MOCK_USER.discordId, username: MOCK_USER.username, gamertag: MOCK_USER.xboxGamertag},
      {discordId: '200000000000000010', username: 'RallyFan', gamertag: 'RallyFan'},
      {discordId: '200000000000000011', username: 'DirtKing', gamertag: 'DirtKing99'},
    ],
  },
  {
    id: 'evt-3',
    slug: 'drift-showdown-20260512',
    title: 'Purple Smoke Drift Showdown',
    type: 'drift',
    status: 'open',
    lifecycle: 'open',
    createdAt: new Date(Date.now() - 1 * day).toISOString(),
    startsAt: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    maxPlayers: EVENT_PLAYER_SLOTS,
    currentPlayers: 3,
    carRuleMode: 'restricted_list',
    maxPi: 700,
    allowedCars: [
      {
        carId: 'c3',
        make: 'Nissan',
        model: 'Silvia S15',
        year: 1999,
        pi: 583,
        maxPi: 700,
        restrictions: ['No AWD swap', 'No engine swap'],
      },
    ],
    voicePolicy: 'optional',
    hostDiscordId: '200000000000000004',
    hostUsername: 'DriftKing_EU',
    rules: '',
    description: 'Tandem drift battle on mountain switchbacks.',
    trackCodes: ['321 654 987'],
    lobbyLeaderGamertag: 'DriftKing_EU',
    participants: [],
  },
  {
    id: 'evt-4',
    slug: 'touge-midnight-20260513',
    title: 'Midnight Touge Run',
    type: 'touge',
    status: 'open',
    lifecycle: 'open',
    createdAt: new Date(Date.now() - 3 * day).toISOString(),
    startsAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    maxPlayers: EVENT_PLAYER_SLOTS,
    currentPlayers: 7,
    carRuleMode: 'anything_goes',
    maxPi: 700,
    additionalCarRestrictions: 'Classic JDM only',
    allowedCars: [],
    voicePolicy: 'required',
    hostDiscordId: '200000000000000005',
    hostUsername: 'TokyoDrift',
    rules: '',
    description: 'Old-school JDM only. Narrow roads, max respect.',
    trackCodes: ['555 666 777', '888 999 000'],
    lobbyLeaderGamertag: 'TokyoDrift',
    participants: [],
  },
  {
    id: 'evt-5',
    slug: 'coastal-cruise-20260514',
    title: 'Coastal Sunrise Sprint',
    type: 'road',
    status: 'full',
    lifecycle: 'open',
    createdAt: new Date(Date.now() - 7 * day).toISOString(),
    startsAt: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString(),
    maxPlayers: EVENT_PLAYER_SLOTS,
    currentPlayers: EVENT_PLAYER_SLOTS,
    carRuleMode: 'anything_goes',
    maxPi: 850,
    additionalCarRestrictions: 'Modern Muscle',
    allowedCars: [],
    voicePolicy: 'optional',
    hostDiscordId: '200000000000000006',
    hostUsername: 'SunriseRacers',
    rules: '',
    description: 'Open-class sprint along the coast at dawn.',
    trackCodes: ['100 200 300'],
    lobbyLeaderGamertag: 'SunriseRacers',
    participants: [],
  },
];

export const MOCK_EVENTS: ForzaEvent[] = MOCK_EVENTS_RAW.map((e) => ({
  ...e,
  coverImageUrl: resolveEventCoverUrl(e.type, e.coverImageUrl),
}));

export function getEventById(id: string): ForzaEvent | undefined {
  return MOCK_EVENTS.find((e) => e.id === id);
}
