/** Stable validation codes — keep in sync with `supabase/functions/_shared/validationCodes.ts`. */
export const VALIDATION_CODES = {
  TITLE_REQUIRED: 'TITLE_REQUIRED',
  TYPE_REQUIRED: 'TYPE_REQUIRED',
  STARTS_AT_REQUIRED: 'STARTS_AT_REQUIRED',
  GUILD_REQUIRED: 'GUILD_REQUIRED',
  CHANNEL_REQUIRED: 'CHANNEL_REQUIRED',
  CONVOY_LEADER_REQUIRED: 'CONVOY_LEADER_REQUIRED',
  CONVOY_LEADER_DISCORD_REQUIRED: 'CONVOY_LEADER_DISCORD_REQUIRED',
  CARS_REQUIRED: 'CARS_REQUIRED',
  PI_RANGE: 'PI_RANGE',
  TARGET_GUILD_LOCKED: 'TARGET_GUILD_LOCKED',
  TARGET_CHANNEL_LOCKED: 'TARGET_CHANNEL_LOCKED',
} as const;

export type ValidationCode = (typeof VALIDATION_CODES)[keyof typeof VALIDATION_CODES];

export const VALIDATION_CODE_LIST = Object.values(VALIDATION_CODES);
