/** Stable API error codes — keep in sync with `src/lib/apiErrorCodes.ts`. */
export const API_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL: 'INTERNAL',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  BAD_REQUEST: 'BAD_REQUEST',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  NOT_FOUND: 'NOT_FOUND',
  BOT_NOT_IN_GUILD: 'BOT_NOT_IN_GUILD',
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  CHANNEL_NOT_TEXT: 'CHANNEL_NOT_TEXT',
  CHANNEL_WRONG_GUILD: 'CHANNEL_WRONG_GUILD',
  BOT_NOT_GUILD_MEMBER: 'BOT_NOT_GUILD_MEMBER',
  BOT_CANNOT_POST: 'BOT_CANNOT_POST',
  EVENT_FULL: 'EVENT_FULL',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  REGISTRATION_AFTER_START: 'REGISTRATION_AFTER_START',
  HOST_CANNOT_JOIN: 'HOST_CANNOT_JOIN',
  LEADER_CANNOT_LEAVE: 'LEADER_CANNOT_LEAVE',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  NOT_DRAFT: 'NOT_DRAFT',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  RESULTS_PARTICIPANTS_ONLY: 'RESULTS_PARTICIPANTS_ONLY',
  PUBLISH_IN_PROGRESS: 'PUBLISH_IN_PROGRESS',
  RESULTS_ALREADY_SUBMITTED: 'RESULTS_ALREADY_SUBMITTED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  GUILD_MEMBER_SEARCH_DISABLED: 'GUILD_MEMBER_SEARCH_DISABLED',
  GROUPS_MAXED: 'GROUPS_MAXED',
  WAITLIST_EMPTY: 'WAITLIST_EMPTY',
  LEADER_ALREADY_IN_LOBBY: 'LEADER_ALREADY_IN_LOBBY',
  LOBBY_NOT_FULL: 'LOBBY_NOT_FULL',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const API_ERROR_CODE_LIST = Object.values(API_ERROR_CODES);
