#!/usr/bin/env node
/**
 * Parse FH6 car list markdown (from https://forza.net/fh6cars) into seed JSON + SQL.
 * Usage: node scripts/parse-fh6cars.mjs [path-to-fh6cars.md]
 */
import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const input = process.argv[2] ?? join(root, '../supabase/seed/fh6cars-source.md');

const md = readFileSync(input, 'utf8');
const cars = [];

for (const line of md.split('\n')) {
  if (!line.startsWith('|') || line.includes('Make') || line.includes('---')) continue;
  const parts = line.split('|').map((s) => s.trim()).filter(Boolean);
  if (parts.length < 5) continue;
  const m = parts[3].match(/^(\d+)\s+([A-Z0-9]+)$/);
  if (!m) continue;

  const make = parts[0];
  const fullName = parts[1];
  const yearMatch = fullName.match(/^(\d{4})\s/);
  const year = yearMatch ? Number(yearMatch[1]) : null;
  const model = yearMatch ? fullName.slice(5).trim() : fullName;

  cars.push({
    make,
    model,
    year,
    pi: Number(m[1]),
    class: m[2],
  });
}

if (cars.length === 0) {
  console.error('No cars parsed — check input file format');
  process.exit(1);
}

const outJson = join(root, '../supabase/seed/fh6cars.json');
writeFileSync(outJson, JSON.stringify(cars, null, 2));

const esc = (s) => s.replace(/'/g, "''");
const values = cars
  .map(
    (c) =>
      `('${esc(c.make)}', '${esc(c.model)}', ${c.year ?? 'NULL'}, ${c.pi}, '${c.class}'::car_class)`,
  )
  .join(',\n  ');

const outSql = join(root, '../supabase/migrations/005_fh6_cars_catalog.sql');
const sql = `-- FH6 official car catalog (${cars.length} cars) — source: https://forza.net/fh6cars
-- Generated by scripts/parse-fh6cars.mjs — re-run parser after list updates

ALTER TYPE car_class ADD VALUE IF NOT EXISTS 'R';

DELETE FROM event_cars;
DELETE FROM cars;

INSERT INTO cars (make, model, year, pi, class) VALUES
  ${values};
`;

writeFileSync(outSql, sql);

console.log(`Parsed ${cars.length} cars`);
console.log(`Wrote ${outJson}`);
console.log(`Wrote ${outSql}`);
