-- Sample events with curated car lists
INSERT INTO discord_guilds (guild_id, guild_name) VALUES ('000000000000000001', 'FORZA.EVENTS Dev') ON CONFLICT (guild_id) DO NOTHING;
INSERT INTO users (discord_id, username, discriminator, xbox_gamertag) VALUES ('000000000000000001', 'FORZA.EVENTS', '0', 'FORZA.EVENTS') ON CONFLICT (discord_id) DO NOTHING;

DELETE FROM event_cars WHERE event_id IN (SELECT id FROM events WHERE slug LIKE 'sample-%');
DELETE FROM events WHERE slug LIKE 'sample-%';


INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-90s-jdm-touge', '90s JDM Touge Night', 'touge', 'open', '000000000000000001', '000000000000000001', now() + interval '30 hours', 580, 'restricted_list', 'general', 'optional', 11, 6, 'Class B Japanese icons from the same era — tight PI band, stock aero, no swaps.', '842 193 405', ARRAY['291 044 118']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Honda' AND year = 1992 AND model ILIKE '%NSX-R%' AND active = true LIMIT 1), 580, ARRAY['No engine swap','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-90s-jdm-touge' AND (SELECT id FROM cars WHERE make = 'Honda' AND year = 1992 AND model ILIKE '%NSX-R%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Nissan' AND year = 1992 AND model ILIKE '%Skyline GT-R%' AND active = true LIMIT 1), 560, ARRAY['No engine swap','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-90s-jdm-touge' AND (SELECT id FROM cars WHERE make = 'Nissan' AND year = 1992 AND model ILIKE '%Skyline GT-R%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Nissan' AND year = 1997 AND model ILIKE '%Skyline GT-R V-Spec%' AND active = true LIMIT 1), 580, ARRAY['No engine swap','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-90s-jdm-touge' AND (SELECT id FROM cars WHERE make = 'Nissan' AND year = 1997 AND model ILIKE '%Skyline GT-R V-Spec%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Toyota' AND year = 1998 AND model ILIKE '%Supra RZ%' AND active = true LIMIT 1), 560, ARRAY['No engine swap','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-90s-jdm-touge' AND (SELECT id FROM cars WHERE make = 'Toyota' AND year = 1998 AND model ILIKE '%Supra RZ%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Mazda' AND year = 1992 AND model ILIKE '%RX-7 Type R%' AND active = true LIMIT 1), 560, ARRAY['No engine swap','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-90s-jdm-touge' AND (SELECT id FROM cars WHERE make = 'Mazda' AND year = 1992 AND model ILIKE '%RX-7 Type R%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-80s-group-b', '80s Group B Gravel', 'dirt', 'open', '000000000000000001', '000000000000000001', now() + interval '54 hours', 580, 'restricted_list', 'general', 'optional', 11, 4, 'Homologation heroes from the same Group B generation — all Class B, similar PI.', '118 402 991', ARRAY['205 881 044']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Audi' AND year = 1984 AND model ILIKE '%Sport quattro%' AND active = true LIMIT 1), 540, ARRAY['Rally tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-80s-group-b' AND (SELECT id FROM cars WHERE make = 'Audi' AND year = 1984 AND model ILIKE '%Sport quattro%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Lancia' AND year = 1986 AND model ILIKE '%Delta S4%' AND active = true LIMIT 1), 580, ARRAY['Rally tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-80s-group-b' AND (SELECT id FROM cars WHERE make = 'Lancia' AND year = 1986 AND model ILIKE '%Delta S4%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Opel' AND year = 1984 AND model ILIKE '%Manta 400%' AND active = true LIMIT 1), 580, ARRAY['Rally tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-80s-group-b' AND (SELECT id FROM cars WHERE make = 'Opel' AND year = 1984 AND model ILIKE '%Manta 400%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-70s-muscle', '70s Muscle Fair Fight', 'road', 'open', '000000000000000001', '000000000000000001', now() + interval '78 hours', 510, 'restricted_list', 'general', 'optional', 11, 8, 'American muscle from the early 1970s — Class C, close PI, period-correct builds.', '601 882 014', ARRAY['442 019 880']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 1970 AND model ILIKE '%Camaro Z28%' AND active = true LIMIT 1), 450, ARRAY['No engine swap']::text[] FROM events e WHERE e.slug = 'sample-70s-muscle' AND (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 1970 AND model ILIKE '%Camaro Z28%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 1970 AND model ILIKE '%Chevelle Super Sport 454%' AND active = true LIMIT 1), 440, ARRAY['No engine swap']::text[] FROM events e WHERE e.slug = 'sample-70s-muscle' AND (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 1970 AND model ILIKE '%Chevelle Super Sport 454%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Dodge' AND year = 1970 AND model ILIKE '%Challenger R/T%' AND active = true LIMIT 1), 460, ARRAY['No engine swap']::text[] FROM events e WHERE e.slug = 'sample-70s-muscle' AND (SELECT id FROM cars WHERE make = 'Dodge' AND year = 1970 AND model ILIKE '%Challenger R/T%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Dodge' AND year = 1969 AND model ILIKE '%Charger R/T%' AND active = true LIMIT 1), 430, ARRAY['No engine swap']::text[] FROM events e WHERE e.slug = 'sample-70s-muscle' AND (SELECT id FROM cars WHERE make = 'Dodge' AND year = 1969 AND model ILIKE '%Charger R/T%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 1970 AND model ILIKE '%Corvette ZR-1%' AND active = true LIMIT 1), 510, ARRAY['No engine swap']::text[] FROM events e WHERE e.slug = 'sample-70s-muscle' AND (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 1970 AND model ILIKE '%Corvette ZR-1%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-wrc-golden', 'WRC Golden Era', 'dirt', 'open', '000000000000000001', '000000000000000001', now() + interval '102 hours', 580, 'restricted_list', 'general', 'optional', 11, 5, '1990s–2000s rally legends — Class B AWD, one decade of evolution, same tire rules.', '224 881 902', ARRAY['901 224 118']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Mitsubishi' AND year = 1995 AND model ILIKE '%Lancer Evolution III%' AND active = true LIMIT 1), 530, ARRAY['Rally tires','AWD']::text[] FROM events e WHERE e.slug = 'sample-wrc-golden' AND (SELECT id FROM cars WHERE make = 'Mitsubishi' AND year = 1995 AND model ILIKE '%Lancer Evolution III%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Subaru' AND year = 1998 AND model ILIKE '%Impreza 22B%' AND active = true LIMIT 1), 580, ARRAY['Rally tires','AWD']::text[] FROM events e WHERE e.slug = 'sample-wrc-golden' AND (SELECT id FROM cars WHERE make = 'Subaru' AND year = 1998 AND model ILIKE '%Impreza 22B%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Mitsubishi' AND year = 2004 AND model ILIKE '%Lancer Evolution VIII%' AND active = true LIMIT 1), 570, ARRAY['Rally tires','AWD']::text[] FROM events e WHERE e.slug = 'sample-wrc-golden' AND (SELECT id FROM cars WHERE make = 'Mitsubishi' AND year = 2004 AND model ILIKE '%Lancer Evolution VIII%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Subaru' AND year = 2004 AND model ILIKE '%IMPREZA WRX STI%' AND active = true LIMIT 1), 560, ARRAY['Rally tires','AWD']::text[] FROM events e WHERE e.slug = 'sample-wrc-golden' AND (SELECT id FROM cars WHERE make = 'Subaru' AND year = 2004 AND model ILIKE '%IMPREZA WRX STI%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-hypercar-sprint', 'Modern Hypercar Sprint', 'road', 'open', '000000000000000001', '000000000000000001', now() + interval '126 hours', 770, 'restricted_list', 'general', 'optional', 11, 3, 'Late-2010s Class S1 supercars — similar PI window, race tires, no aero cheese.', '331 902 118', ARRAY['902 331 044']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'BMW' AND year = 2016 AND model ILIKE '%M4 GTS%' AND active = true LIMIT 1), 720, ARRAY['Race tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-hypercar-sprint' AND (SELECT id FROM cars WHERE make = 'BMW' AND year = 2016 AND model ILIKE '%M4 GTS%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Audi' AND year = 2016 AND model ILIKE '%R8 V10 plus%' AND active = true LIMIT 1), 740, ARRAY['Race tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-hypercar-sprint' AND (SELECT id FROM cars WHERE make = 'Audi' AND year = 2016 AND model ILIKE '%R8 V10 plus%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 2015 AND model ILIKE '%Corvette Z06%' AND active = true LIMIT 1), 770, ARRAY['Race tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-hypercar-sprint' AND (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 2015 AND model ILIKE '%Corvette Z06%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Porsche' AND year = 2019 AND model ILIKE '%911 GT3 RS%' AND active = true LIMIT 1), 760, ARRAY['Race tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-hypercar-sprint' AND (SELECT id FROM cars WHERE make = 'Porsche' AND year = 2019 AND model ILIKE '%911 GT3 RS%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-2000s-exotic-cup', '2000s Exotic Cup', 'road', 'open', '000000000000000001', '000000000000000001', now() + interval '150 hours', 690, 'restricted_list', 'general', 'optional', 11, 7, 'Class A exotics from the 2000s — matched performance, sports tires.', '442 118 902', ARRAY['118 442 331']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Ford' AND year = 2005 AND model ILIKE '%Ford GT%' AND active = true LIMIT 1), 690, ARRAY['Sports tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-2000s-exotic-cup' AND (SELECT id FROM cars WHERE make = 'Ford' AND year = 2005 AND model ILIKE '%Ford GT%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Porsche' AND year = 2004 AND model ILIKE '%911 GT3%' AND active = true LIMIT 1), 680, ARRAY['Sports tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-2000s-exotic-cup' AND (SELECT id FROM cars WHERE make = 'Porsche' AND year = 2004 AND model ILIKE '%911 GT3%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 2002 AND model ILIKE '%Corvette Z06%' AND active = true LIMIT 1), 620, ARRAY['Sports tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-2000s-exotic-cup' AND (SELECT id FROM cars WHERE make = 'Chevrolet' AND year = 2002 AND model ILIKE '%Corvette Z06%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Alfa Romeo' AND year = 2007 AND model ILIKE '%8C Competizione%' AND active = true LIMIT 1), 650, ARRAY['Sports tires','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-2000s-exotic-cup' AND (SELECT id FROM cars WHERE make = 'Alfa Romeo' AND year = 2007 AND model ILIKE '%8C Competizione%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-drift-legends', 'Drift Legends', 'drift', 'open', '000000000000000001', '000000000000000001', now() + interval '174 hours', 560, 'restricted_list', 'general', 'optional', 11, 9, '90s–2000s RWD drift platforms — Class B, similar power, drift tires required.', '991 224 442', ARRAY['224 991 118']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Mazda' AND year = 1992 AND model ILIKE '%RX-7 Type R%' AND active = true LIMIT 1), 560, ARRAY['Drift tires','RWD','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-drift-legends' AND (SELECT id FROM cars WHERE make = 'Mazda' AND year = 1992 AND model ILIKE '%RX-7 Type R%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Nissan' AND year = 2002 AND model ILIKE '%Silvia Spec-R%' AND active = true LIMIT 1), 560, ARRAY['Drift tires','RWD','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-drift-legends' AND (SELECT id FROM cars WHERE make = 'Nissan' AND year = 2002 AND model ILIKE '%Silvia Spec-R%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Toyota' AND year = 1998 AND model ILIKE '%Supra RZ%' AND active = true LIMIT 1), 540, ARRAY['Drift tires','RWD','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-drift-legends' AND (SELECT id FROM cars WHERE make = 'Toyota' AND year = 1998 AND model ILIKE '%Supra RZ%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Toyota' AND year = 1997 AND model ILIKE '%Chaser%' AND active = true LIMIT 1), 520, ARRAY['Drift tires','RWD','No engine swap']::text[] FROM events e WHERE e.slug = 'sample-drift-legends' AND (SELECT id FROM cars WHERE make = 'Toyota' AND year = 1997 AND model ILIKE '%Chaser%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-lightweight-roadsters', 'Lightweight Roadster Cup', 'road', 'open', '000000000000000001', '000000000000000001', now() + interval '198 hours', 510, 'restricted_list', 'general', 'optional', 11, 2, '2010s Class C RWD roadsters — same lightweight philosophy, close PI.', '014 601 882', ARRAY['882 014 601']::text[], NULL, 'FORZA.EVENTS', true, 'UTC', 'global');
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Mazda' AND year = 2016 AND model ILIKE '%MX-5%' AND active = true LIMIT 1), 510, ARRAY['Sports tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-lightweight-roadsters' AND (SELECT id FROM cars WHERE make = 'Mazda' AND year = 2016 AND model ILIKE '%MX-5%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Subaru' AND year = 2013 AND model ILIKE '%BRZ%' AND active = true LIMIT 1), 480, ARRAY['Sports tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-lightweight-roadsters' AND (SELECT id FROM cars WHERE make = 'Subaru' AND year = 2013 AND model ILIKE '%BRZ%' AND active = true LIMIT 1) IS NOT NULL;
INSERT INTO event_cars (event_id, car_id, max_pi, car_restrictions) SELECT e.id, (SELECT id FROM cars WHERE make = 'Toyota' AND year = 2013 AND model ILIKE '%86%' AND active = true LIMIT 1), 480, ARRAY['Sports tires','No Forza aero']::text[] FROM events e WHERE e.slug = 'sample-lightweight-roadsters' AND (SELECT id FROM cars WHERE make = 'Toyota' AND year = 2013 AND model ILIKE '%86%' AND active = true LIMIT 1) IS NOT NULL;

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-60s-pony-open', '60s Pony Car Cruise', 'road', 'open', '000000000000000001', '000000000000000001', now() + interval '222 hours', 480, 'anything_goes', 'general', 'optional', 11, 4, 'Open build capped at 480 PI — period-correct 1960s American coupes.', '880 442 019', ARRAY[]::text[], '1960s American pony cars and muscle — Class C or below', 'FORZA.EVENTS', true, 'UTC', 'global');

INSERT INTO events (slug, title, type, status, host_discord_id, guild_id, starts_at, max_pi, car_rule_mode, car_setup_mode, voice_policy, max_players, current_players, description, event_share_code, track_codes, additional_car_restrictions, lobby_leader_gamertag, lobby_leader_is_host, timezone_hint, region)
VALUES ('sample-touge-open-90s-b', '90s Touge Open (Class B)', 'touge', 'open', '000000000000000001', '000000000000000001', now() + interval '246 hours', 570, 'anything_goes', 'general', 'optional', 11, 1, 'Open PI build up to 570 — any 1990s JDM Class B machine.', '405 842 193', ARRAY['193 405 842']::text[], '1990s Japanese sports cars — Class B only', 'FORZA.EVENTS', true, 'UTC', 'global');

